require:
  - rubocop-rails

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/ContextWording:
  Enabled: false
