require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

plugins:
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120
  Exclude:
    - "config/**/*"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 20

Metrics/ModuleLength:
  Max: 180

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Minitest/MultipleAssertions:
  Max: 5
