require:
  - rubocop-rails

plugins:
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
