name: skateparks-test
services:
  skateparks-db-test:
    image: postgres:18-alpine
    container_name: postgres-17-test
    volumes:
      - postgres_data_test:/var/lib/postgresql
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
  skateparks-redis-test:
    image: redis:8-alpine
    container_name: skateparks-redis-test
    command: redis-server
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
  skateparks-web-test:
    container_name: rails-app-test
    build:
      context: .
      dockerfile: Dockerfile.test
    command: "./bin/rails server -b 0.0.0.0 -p 3003 --pid tmp/pids/server_test.pid"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - REDIS_URL=${REDIS_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - RUBY_YJIT_ENABLE=0
    volumes:
      - app-storage:/rails/storage
      - ${CODEBASE_VOLUME}:/rails
    depends_on:
      - skateparks-db-test
      - skateparks-redis-test
    ports:
      - "3003:3003"

volumes:
  postgres_data_test: {}
  app-storage: {}
  redis_data: {}
