# fly.toml app configuration file generated for skateparks on 2023-12-26T12:44:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skateparks"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/healthcheck"
    protocol = "http"
    tls_skip_verify = false
    [checks.status.headers]
      X-Forwarded-Proto = "https"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"
[deploy]
  release_command = "./bin/rails db:prepare"
[mounts]
  source="skateparks_data"
  destination="/data"
