test:
  service: Disk
  root: <%= Rails.root.join("storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: eu-central-1
  bucket: skateparks.gr
  public: true
  upload:
    cache_control: "private, max-age=<%= 1.day.to_i %>"

cloudinary:
  service: Cloudinary
